#./mvnw clean package
#podman build -f src/main/docker/Containerfile -t app-spring .
#podman run -i --rm -p 8080:8080 app-spring
#

#FROM registry.access.redhat.com/ubi8/openjdk-8:1.16-1.1687182685
FROM registry.access.redhat.com/ubi8/openjdk-11:1.11

USER root

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*.jar /work

EXPOSE 8080
USER 1001

CMD ["java", "-jar", "chapter-3-spring-rest-json-0.0.1-SNAPSHOT.jar"]